name: "Datarepo GitHub Actions"
description: "Runs various commands via GitHub Actions."
branding:
  icon: "terminal"
  color: "purple"
inputs:
  actions_subcommand:
    description: "subcommand to execute."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.actions_subcommand }}
