name: "Commits and Merges Code"
description: "Runs various commands via GitHub Actions."
branding:
  icon: "terminal"
  color: "purple"
inputs:
  actions_subcommand:
    description: "subcommand to execute."
    required: false
runs:
  using: "docker"
  image: "./Dockerfile"
