name: "Commits and Merges Code"
description: "Commits and merges code changed in earlier steps of workflow"
branding:
  icon: "terminal"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
